# SPDX-License-Identifier: MIT
description: ZMK WS2812/SK6812 Addressable RGB LED Strip

compatible: "zmk,ws2812"

properties:
  pin:
    type: phandle-array
    required: true
    description: Data output pin for the LED strip

  pin-secondary:
    type: phandle-array
    required: false
    description: Secondary data output pin for the LED strip (optional)

  chain-length:
    type: int
    required: true
    description: Number of LEDs in the strip

  label:
    type: string
    required: false
    description: Human readable name
