# SPDX-License-Identifier: MIT
description: ZMK WS2812/SK6812 Addressable RGB LED Strip

compatible: "zmk,ws2812"

properties:
  gpios:
    type: phandle-array
    required: false
    description: Data output pin for the LED strip

  pin:
    type: phandle-array
    required: false
    description: Data output pin for the LED strip (alternative to gpios)

  chain-length:
    type: int
    required: true
    description: Number of LEDs in the strip

  color-order:
    type: string
    required: false
    description: Color order for the LED strip (e.g., RGB, GRB, etc.)

  label:
    type: string
    required: true
    description: Human readable name
